### ISSUE TITLE
Task not running

### ISSUE THREAD

**Issue by robstott** [prachigauriar/Task#31]
Hi there,

Firstly, I really like the look of this framework. It could be really useful for me. However, I'm falling at the first hurdle here. My code below results in Task C & Task A being executed, but Task B is never executed. I guess I'm missing the point somewhere and doing something dumb. 

Can you advise please?

Thanks
Rob

```
	//create some workflows
	TSKWorkflow *workflow = [[TSKWorkflow alloc] initWithName:@"Workflow Test"];
	
	TSKBlockTask *taskA =[[TSKBlockTask alloc] initWithBlock:^(TSKTask * _Nonnull task) {
		
		NSLog(@"Task A");
		
	}];
	
	TSKBlockTask *taskB =[[TSKBlockTask alloc] initWithBlock:^(TSKTask * _Nonnull task) {
		
		NSLog(@"Task B");

	}];
	
	TSKBlockTask *taskC =[[TSKBlockTask alloc] initWithBlock:^(TSKTask * _Nonnull task) {
		
		NSLog(@"Task C");

	}];
	
	
	[workflow addTask:taskA prerequisites:nil];
	[workflow addTask:taskB prerequisites:taskA, nil];
	[workflow addTask:taskC prerequisites: nil];

	[workflow start];

```

**Comment by dfowjtm** [comment]
Hi @robstott - when using a block task, you need to invoke either `‑finishWithResult:` or `‑failWithError:` on the `task` parameter when the code in your block finishes executing. This will signal to the block task that it is "done" and that the workflow can continue.

You can also take a look at the documentation in https://github.com/Ticketmaster/Task/blob/master/Task/Tasks/TSKBlockTask.h

Hope this helps!

**Comment by prachigauriar** [comment]
In addition to what @dfowjtm said, you also need to be sure that you’re retaining your workflow. Unlike operation queues, there’s no good answer for when a workflow’s life should implicitly end. They can be reset and their tasks can be retried after failing. As such, we’ve chosen not to automatically maintain a strong reference to the workflow while tasks are running. Instead, it is the responsibility of the caller to maintain a strong reference to their workflow until all tasks are complete. Typically that means putting it in a property, though it’s pretty trivial to create a wrapper object that keeps a workflow alive until all its tasks are done executing. The latter approach precludes you from doing most of the interesting things that workflows provide though.

**Comment by robstott** [comment]
Awesome. I can't believe I missed that. Got it working perfectly now.

Thanks, both, for your help.
